-- Use the database
USE ProjectTracker;

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS ProjectDetail;
DROP TABLE IF EXISTS ProjectConsultant;
DROP TABLE IF EXISTS Consultant;
DROP TABLE IF EXISTS Login;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS Client;

-- Create Client table
CREATE TABLE Client (
    ClientID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    Company VARCHAR(255) NOT NULL UNIQUE,
    Street VARCHAR(50) NOT NULL,
    City VARCHAR(50) NOT NULL,
    State CHAR(2) NOT NULL,
    PostalCode CHAR(5) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    EmailAddress VARCHAR(50) NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create Project table
CREATE TABLE Project (
    ProjectID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ClientID SMALLINT NOT NULL,
    ProjectName VARCHAR(255) NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE,
    CreatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ClientID) REFERENCES Client(ClientID)
);

-- Create Login table
CREATE TABLE Login (
    LoginID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create Consultant table
CREATE TABLE Consultant (
    ConsultantID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    LoginID SMALLINT NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    EmailAddress VARCHAR(50) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (LoginID) REFERENCES Login(LoginID)
);

-- Create ProjectConsultant table
CREATE TABLE ProjectConsultant (
    ProjectID SMALLINT NOT NULL,
    ConsultantID SMALLINT NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ProjectID, ConsultantID),
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID),
    FOREIGN KEY (ConsultantID) REFERENCES Consultant(ConsultantID)
);

-- Create ProjectDetail table
CREATE TABLE ProjectDetail (
    DetailID INT AUTO_INCREMENT PRIMARY KEY,
    ProjectID SMALLINT NOT NULL,
    Task VARCHAR(100) NOT NULL,
    Hours DECIMAL(10,2) NOT NULL,
    WorkDate DATE NOT NULL,
    CreatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID)
);